### ISSUE TITLE
How to generate unconditional image?

### ISSUE THREAD

**Issue by wodsoe** [CompVis/taming-transformers#10]
Hi,
How to generate unconditional image?
Thank you!

**Comment by AmberCheng** [comment]
The same question~ 
I found the paper has the results of generating half-image, but I cannot found it in the repo.

**Comment by CoreloneH** [comment]
Hi, I have the same question too. Do you have fixed the problem?

**Comment by wodsoe** [comment]
No,I don't know.

**Comment by Thierryonre** [comment]
This [colab](https://colab.research.google.com/github/ak9250/taming-transformers/blob/master/tamingtransformerscolab.ipynb#scrollTo=xatBjPGHxlcD) generates similar images as they have the same segmentation but it also allows you to change a few parameters as well.
So I was thinking about using a data efficient GAN or SinGAN to generate a segmentation and then use this to transform it into an image.

**Comment by sindhuharish** [comment]
Has this approach been extended to use BERT based transformer instead of GPT?

**Comment by Thierryonre** [comment]
No idea :/

**Comment by PanayiotaK** [comment]
I'm interested in this as well.
