### ISSUE TITLE
CelebA-HQ

### ISSUE THREAD

**Issue by benjaminklein** [CompVis/taming-transformers#11]
Regarding CelebA-HQ - in the link you shared there are instructions on how to create tfrecords for CelebA-HQ but not the npy which are required in your code. Can you please provide some guidance on this? 
Thank you

**Comment by PeterouZh** [comment]
You could download the images at this [link](https://github.com/suvojit-0x55aa/celebA-HQ-dataset-download). Then you need to modify a few lines of code to load the images directly rather than the npy files.

**Comment by benjaminklein** [comment]
Thank you
