### ISSUE TITLE
about sflckr transformer config

### ISSUE THREAD

**Issue by coralreefman** [CompVis/taming-transformers#110]
I trained the sflckr first stage and cond stage respectively but when I try to train the transformer I run into:
`IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)` in the forward function of the transformer.
I use the Examples class from sflckr.py to load the data which worked fine for training the cond stage (one pointing to train and one to val directory).
Any advice  would be greatly appreciated.

**Comment by Firmiana1220** [comment]
> I trained the sflckr first stage and cond stage respectively but when I try to train the transformer I run into: `IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)` in the forward function of the transformer. I use the Examples class from sflckr.py to load the data which worked fine for training the cond stage (one pointing to train and one to val directory). Any advice would be greatly appreciated.

I have the same problem. Have you solved it?

**Comment by HappyDeepLearning** [comment]
> I trained the sflckr first stage and cond stage respectively but when I try to train the transformer I run into: `IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)` in the forward function of the transformer. I use the Examples class from sflckr.py to load the data which worked fine for training the cond stage (one pointing to train and one to val directory). Any advice would be greatly appreciated.

I have the same problem. I find the key problem is this [line ](https://github.com/CompVis/taming-transformers/blob/master/taming/models/cond_transformer.py#L94), `c_indices `and `a_indices` are different shapes. The shape of `c_indices ` is (B, D). The shape of `a_indices` is (B*D, ). 
I only add the below codes to function [`encode_to_c`](https://github.com/CompVis/taming-transformers/blob/master/taming/models/cond_transformer.py#L176). This work for me.
```
if len(indices.shape) > 2 or len(indices.shape) == 1: 
    indices = indices.view(c.shape[0], -1)
```

**Comment by LittleQBerry** [comment]
So how to create a correct config file for sflckr transformer phase?  Thanks for your help.

**Comment by kaihe** [comment]
> I trained the sflckr first stage and cond stage respectively but when I try to train the transformer I run into: `IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)` in the forward function of the transformer. I use the Examples class from sflckr.py to load the data which worked fine for training the cond stage (one pointing to train and one to val directory). Any advice would be greatly appreciated.

How did you generate sflckr dataset? Is it a random window of 256x256 to crop the large image?

**Comment by coralreefman** [comment]
@LittleQBerry the solution by @HappyDeepLearning works for me, at least it doesn't give any errors and the transformer seems to train correctly.
