### ISSUE TITLE
Use text as Condition?

### ISSUE THREAD

**Issue by CoreloneH** [CompVis/taming-transformers#13]

**Comment by CoreloneH** [comment]
Hi, Thanks for your wonderful works! I wonder have you tried using text as the condition to generate images, such as using MS COCO dataset? If you have tried, does it work well?

**Comment by rromb** [comment]
Good idea! We haven't done extensive experiments for this task, but it's a straightforward code modification (assuming a suitable tokenizer). COCO should be a good starting point, but performance might be limited due to the small dataset and vocabulary size.

**Comment by rromb** [comment]
I will close this for now, but make sure to check out [this awesome github repo](https://github.com/lucidrains/DALLE-pytorch) which aims at rebuilding OpenAI's DALL-E model. @lucidrains added the option to either use the official DALL-E VAE (downsampling by a factor of 8, resulting in a sequence of length 32x32=1024) or our VQGAN with a codebook size of 1024 (downsampling by a factor of 16, resulting in a sequence of length 16x16=256 when using 256x256 images).

**Comment by Guthman** [comment]
Hi, you're probably too busy for this, but in the paper you mention doing class-conditional image synthesis with RIN. And the quote below (from the paper) implies that you could do so without having to train a second VQGAN:

"If the conditioning information c has spatial extent, we first learn another VQGAN to obtain again an index-based representation r ∈ {0, . . . , |Zc |−1}hc ×wc with the newly obtained codebook Zc"

Are you able to share your code for accomplishing this (in a Github Gist for example)? I can't find it in the repo.
