### ISSUE TITLE
upload CelebA-HQ-256 

### ISSUE THREAD

**Issue by lukovnikov** [CompVis/taming-transformers#177]
Could you please upload the CelebA-HQ-256 dataset? If possible, in a normal format (as separate image files, or as numpy array).
It is really difficult to reproduce the dataset using the instructions from PGGAN because some packages are outdated and the 256x256 images would actually require less downloading than just the delta's from PGGAN.

**Comment by lukovnikov** [comment]
In case anyone wants them, I uploaded CelebaHQ-256 images here: https://www.kaggle.com/datasets/denislukovnikov/celebahq256-images-only
and FFHQ-256 here: https://www.kaggle.com/datasets/denislukovnikov/ffhq256-images-only

**Comment by Alii-Ganjj** [comment]
Hi @lukovnikov,

Thanks for your great effort to reproduce the dataset. I have a question about indexing of the files. The dataset that you provided on Kaggle has 27k train and 3k validation images. However, this repo selects 25k train and 5k validation in the [index files](https://github.com/CompVis/taming-transformers/blob/master/data/celebahqtrain.txt). I wanted to combine the train and validation sets that you provided but I found they both start from index 0.
Do you know what is the difference here?

Thank you in advance.
