### ISSUE TITLE
pytorch light issue

### ISSUE THREAD

**Issue by willyk26** [CompVis/taming-transformers#189]
`ImportError                               Traceback (most recent call last)
[<ipython-input-1-345a6d4ed2bc>](https://localhost:8080/#) in <module>
      7 sys.path.append(".")
      8 sys.path.append('./taming-transformers')
----> 9 from taming.models import vqgan # checking correct import from taming

1 frames
[/content/taming-transformers/main.py](https://localhost:8080/#) in <module>
     10 from pytorch_lightning.trainer import Trainer
     11 from pytorch_lightning.callbacks import ModelCheckpoint, Callback, LearningRateMonitor
---> 12 from pytorch_lightning.utilities.distributed import rank_zero_only
     13 
     14 from taming.data.utils import custom_collate

ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

this is from the example colab of superresolution`

**Comment by GwendalC** [comment]
ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)

-> on this notebook
https://colab.research.google.com/drive/1sc-Qa7feIatfWkhHWFu01pzeE2AVinmn?usp=sharing#scrollTo=VA1PHoJrRiK9

thanks a lot for your help

**Comment by GwendalC** [comment]
I think !pip install --upgrade pytorch-lightning did the job for me

**Comment by carmocca** [comment]
Hi all, I opened a PR with the fix: #190

@rromb Could you take a look? It's a one-line fix
