### ISSUE TITLE
how does the quantization book avoid trivial solution?

### ISSUE THREAD

**Issue by xwplusb** [CompVis/taming-transformers#191]
I tried training my own module, but the quantization stage always collapsed into trivial solution, i.e. all features are indexed to the same entry, I use all the same training procedure,  has anyone come across this issues? or it is just me configuring something wrong?

**Comment by xwplusb** [comment]
Ok, I found a normalizing step in [VQVAE](https://github.com/rosinality/vq-vae-2-pytorch/blob/ef5f67c46f93624163776caec9e0d95063910eca/vqvae.py#L53)

closing this issue  :smile:

**Comment by Marcelo5444** [comment]
Why this normalization avoids the collapse? @xwplusb
