### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ak9250** [CompVis/taming-transformers#2]
Hi, can you please add a google colab for inference thanks

**Comment by Devetec** [comment]
@ak9250 how did you run it for the tweet? Thanks, devetec

**Comment by ak9250** [comment]
@Devetec I setup a colab notebook, used ngrok with streamlit to run the demo

**Comment by Devetec** [comment]
@ak9250 is it possible for you to share it 😃 thanks!

If not, still, thanks!

**Comment by ak9250** [comment]
@Devetec see notebook here https://github.com/ak9250/taming-transformers/blob/master/tamingtransformerscolab.ipynb

**Comment by pesser** [comment]
Thanks for the suggestion! Just added a very minimal colab notebook and only saw your notebook now. That's such a great way to run a streamlit demo via colab! If you don't mind, I'd also put a link to your notebook in the readme.

**Comment by ak9250** [comment]
@pesser thanks sure that would be great, although your notebook is much more clearer and easier to use imo
