### ISSUE TITLE
Possible to get feedback on this paper summary

### ISSUE THREAD

**Issue by ayulockin** [CompVis/taming-transformers#21]
Hi Folks,

Congrats on this amazing paper. I really enjoyed reading the paper. I would love to get your feedback on my [paper summary](https://wandb.ai/ayush-thakur/taming-transformer/reports/-Overview-Taming-Transformers-for-High-Resolution-Image-Synthesis---Vmlldzo0NjEyMTY) for this paper. 

Regards.

**Comment by kleinicke** [comment]
The last step between theory and application is a bit short. You don't mention segmentation masks at all.

**Comment by rromb** [comment]
Very cool! The only thing I noticed when skimming over the report is that we use a _perceptual_ instead of a perpetual loss. We linked your report in the README.
