### ISSUE TITLE
Vector Quantization loss rises in training

### ISSUE THREAD

**Issue by OrangeSodahub** [CompVis/taming-transformers#219]
Hi, guys, I may want to ask for help with the training of a VQModel from scratch, while in my case, the vq loss rises in the middle of training process, while the reconstruction loss kept decrease, the vq loss kept rises to a large level.
I'm really confused about it, is there anyone know how to solve it or ever encountered this issue?

**Comment by OrangeSodahub** [comment]
Solved.

**Comment by jasong-ovo** [comment]
I meet the same phenomenon. How did you solve it ?

**Comment by OrangeSodahub** [comment]
You could check if there is something wrong with the gradient of each parameter of your model first
