### ISSUE TITLE
Invalid version: '0.10.1,<0.11'

### ISSUE THREAD

**Issue by EinfachYan** [CompVis/taming-transformers#220]
it's my first time running anaconda, got this error   

[ File "c:\users\dell\anaconda3\envs\taming\lib\site-packages\packaging\version.py", line 198, in __init__
     raise InvalidVersion(f"Invalid version: '{version}'")
 packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'](url)

I tried
`pip install packaging==21.3`
but it didn't work

what might be the problem?

**Comment by aamijar** [comment]
you can try this
`pip install transformers --upgrade`

**Comment by BasDiaz** [comment]
The repo seems quite broken. I was able to avoid this error commenting out `require_version_core(deps[pkg])` in the `transformers.dependency_versions_check` file. Definitely not a real fix but a workaround

**Comment by chuanshuogushi** [comment]
I solved this by
`pip install transformers==4.19.2`

**Comment by EinfachYan** [comment]
This error refers to the version of tokenizers, which must be less than 0.11. 
I downloaded 0.10.3, which is an older version and cannot be directly downloaded using conda or pip; otherwise, it will result in the error 'Could not build wheels for tokenizers'. 
It requires a Rust compiler. One of the methods is to download Visual Studio and then install the C++ components.

**Comment by EinfachYan** [comment]
> The repo seems quite broken. I was able to avoid this error commenting out `require_version_core(deps[pkg])` in the `transformers.dependency_versions_check` file. Definitely not a real fix but a workaround

This repo is a bit old, and the libraries it uses have been updated many times.
 We need to downgrade these libraries to run it.

**Comment by EinfachYan** [comment]
> you can try this `pip install transformers --upgrade`

thank you

**Comment by EinfachYan** [comment]
> I solved this by `pip install transformers==4.19.2`

thank you
