### ISSUE TITLE
How to train the transformer after training the vqgan model？

### ISSUE THREAD

**Issue by RichardXue123** [CompVis/taming-transformers#232]
I followed the section "Training on custom data" and got a vqgan model. How to train the transformer using my own vqgan model？

**Comment by CreamyLong** [comment]
The transformer and gan are trained at the same time.

**Comment by RichardXue123** [comment]
> The transformer and gan are trained at the same time.

then how could i use the transformer & gan to generate a image?

**Comment by gdjmck** [comment]
> > The transformer and gan are trained at the same time.
> 
> then how could i use the transformer & gan to generate a image?

you could check out the colab link in readme.

**Comment by Ontheroad123** [comment]
> The transformer and gan are trained at the same time.

the 'custom_vqgan.yaml'  load the model 'taming.models.vqgan.VQModel', without 'Net2NetTransformer', why transformer is trained at the same time?

**Comment by RichardXue123** [comment]
> > The transformer and gan are trained at the same time.
> 
> the 'custom_vqgan.yaml' load the model 'taming.models.vqgan.VQModel', without 'Net2NetTransformer', why transformer is trained at the same time?

So if I want to use my custom data to train using the source code of this project, then I can only train the VQGAN network without the transformer, right? And I can only do image reconstruction and not image generation, is that true?

**Comment by Ontheroad123** [comment]
> > > The transformer and gan are trained at the same time.
> > 
> > 
> > the 'custom_vqgan.yaml' load the model 'taming.models.vqgan.VQModel', without 'Net2NetTransformer', why transformer is trained at the same time?
> 
> So if I want to use my custom data to train using the source code of this project, then I can only train the VQGAN network without the transformer, right? And I can only do image reconstruction and not image generation, is that true?

VQGAN have two stages, first stage is encoder and decoder,  second stage is  transformer and decoder  for generation, so if you do image reconstruction, i think it's same as vqvae.

**Comment by RichardXue123** [comment]
> > > > The transformer and gan are trained at the same time.
> > > 
> > > 
> > > the 'custom_vqgan.yaml' load the model 'taming.models.vqgan.VQModel', without 'Net2NetTransformer', why transformer is trained at the same time?
> > 
> > 
> > So if I want to use my custom data to train using the source code of this project, then I can only train the VQGAN network without the transformer, right? And I can only do image reconstruction and not image generation, is that true?
> 
> VQGAN have two stages, first stage is encoder and decoder, second stage is transformer and decoder for generation, so if you do image reconstruction, i think it's same as vqvae.

thanks a lot. But how can i generate a picture after training the custom data? Can we communicate more through email？my email is [richardxue@sjtu.edu.cn](url)

**Comment by RichardXue123** [comment]
i did it by writing a transformer yaml file based on my custom vqgan model.

**Comment by zxb-0** [comment]
> 我通过编写一个基于我的自定义 VQGAN 模型的 transformer YAML 文件来做到这一点。

@RichardXue123  I would like to see your customized YAML file, can I

**Comment by RichardXue123** [comment]
> > 我通过编写一个基于我的自定义 VQGAN 模型的 transformer YAML 文件来做到这一点。
> 
> @RichardXue123 I would like to see your customized YAML file, can I

[custom_transformer.txt](https://github.com/CompVis/taming-transformers/files/14447121/custom_transformer.txt)

**Comment by zxb-0** [comment]
> 

> > > 我通过编写一个基于我的自定义 VQGAN 模型的 transformer YAML 文件来做到这一点。
> > 
> > 
> > 我想看看你定制的YAML文件，我可以吗
> 
> [custom_transformer.txt](https://github.com/CompVis/taming-transformers/files/14447121/custom_transformer.txt)

@RichardXue123  thank you very much
