### ISSUE TITLE
pip installable package

### ISSUE THREAD

**Issue by lucidrains** [CompVis/taming-transformers#30]
Hi! Thank you for the great paper :)

I am the owner of https://github.com/lucidrains/DALLE-pytorch and was thinking of offering the users a way to train DALL-E using your pretrained VQ-GAN, specifically the one with a codebook of size 1024. https://github.com/lucidrains/DALLE-pytorch/pull/75 I was wondering if you would be open to making your repository a pip installable package, with all the necessary dependencies (omegaconf and pytorch-lightning), so that it could be installed with 

```bash
$ pip install taming-transformers
```

followed by

```python
from taming.model.vqgan import VQModel
```

**Comment by pesser** [comment]
That sounds exciting! :star_struck: 
```
pip install taming-transformers
```
should now work, although we haven't tested it exhaustively - so please let us know if there are any problems with it.
Looking forward to see a text-to-image model with VQGAN!

**Comment by lucidrains** [comment]
@pesser thank you Patrick!! :pray: :pray: :pray:

**Comment by afiaka87** [comment]
Hey! Great work on the recent releases! Has the wheel been updated on PyPi? I'm not seeing a version number bump yet and I don't believe the `GumbelVQ` class we're trying to access is available from the pip package yet.

**Comment by rom1504** [comment]
hi @pesser it would be great to update the pip package so we could use the new GumbelVQ class. Could you please update it ?
