### ISSUE TITLE
Straight-through estimator

### ISSUE THREAD

**Issue by sbkim052** [CompVis/taming-transformers#35]
Thank you for sharing your amazing work.

Could you tell me where is the implementation of the "straight-through estimator" for training the encoder?

**Comment by rromb** [comment]
Hi

The following line of code in the `VectorQuantizer` module does the trick.
https://github.com/CompVis/taming-transformers/blob/1bbc027acb6a47e4eb348d611f9af53f1038ffee/taming/modules/vqvae/quantize.py#L73

Hope this helps :)

**Comment by sbkim052** [comment]
Thank you:)
One simple question, for training the auto encoder and codebook,
did you use all the dataset in ImageNet? If not, which categories did you use in ImageNet?
