### ISSUE TITLE
How much VRAM does it take to train COCO-Stuff/ADE20K transformer models?

### ISSUE THREAD

**Issue by lytning98** [CompVis/taming-transformers#36]
Thank you for sharing this great work!

Could you give more information on training COCO-Stuff/ADE20K transformer models?
I got OOM even with **bach-size of 1** when training these transformer models with the hyperparameters specified in the appendix on a GPU with  11GB VRAM. Is this expected? If so, what's the minimum amount of VRAM per GPU to train these conditional models?

**Comment by rromb** [comment]
Hi! 
Yes, this is expected. Since the first release of our work we upgraded the models on COCO and ADE (in terms of #parameters), which we also mention in the recent version on [arxiv](https://arxiv.org/abs/2012.09841v2). Using 16-bit precision and a batch-size of 1, these models use ~20 GB VRAM.

**Comment by lytning98** [comment]
Thanks!

**Comment by yc-cui** [comment]
> Hi! Yes, this is expected. Since the first release of our work we upgraded the models on COCO and ADE (in terms of #parameters), which we also mention in the recent version on [arxiv](https://arxiv.org/abs/2012.09841v2). Using 16-bit precision and a batch-size of 1, these models use ~20 GB VRAM.

It seems that your `Net2NetTransformer` did not consider `batch size > 1`. In your code :
```python
    def get_input(self, key, batch):
        x = batch[key]
        if len(x.shape) == 3:
            x = x[..., None]
        if len(x.shape) == 4:
            x = x.permute(0, 3, 1, 2).to(memory_format=torch.contiguous_format)
        if x.dtype == torch.double:
            x = x.float()
        return x
``` 
When batch is a list contains mutil samples, will produce `TypeError: list indices must be integers or slices, not str`

**Comment by yc-cui** [comment]
> Hi! Yes, this is expected. Since the first release of our work we upgraded the models on COCO and ADE (in terms of #parameters), which we also mention in the recent version on [arxiv](https://arxiv.org/abs/2012.09841v2). Using 16-bit precision and a batch-size of 1, these models use ~20 GB VRAM.

By the way, how do you use `16-bit precision`? I tried to add `precision: 16` in lightning's trainer config. However, it always leads `NaN` loss .
