### ISSUE TITLE
Request:Test the model without downloading the whole dataset.

### ISSUE THREAD

**Issue by sanmeow** [CompVis/taming-transformers#4]
Is there a easier way to test out D-RIN and FacesHQ models?The Imagenet is just too big for trying out the result to see how it works.Wish has a way to test 10 example like the S-FLCKR model.Thanks!

The S-FLCKR model is so mind blowing incredible! Great work!

**Comment by pesser** [comment]
Thanks @sanmeow ! Indeed, downloading imagenet to try out the model is a bit overkill :) Added a couple of D-RIN examples in the repo, see the updated [instructions for the D-RIN demo](https://github.com/CompVis/taming-transformers/#d-rin). Have fun!

**Comment by sanmeow** [comment]
Thanks! It works! Very cool result.
