### ISSUE TITLE
beta term does not correctly apply to the loss term in VQ-VAE 

### ISSUE THREAD

**Issue by richcmwang** [CompVis/taming-transformers#46]
Is the beta supposed to be applied to the commit loss where z_q is frozen rather than z is frozen?

https://github.com/CompVis/taming-transformers/blob/1bbc027acb6a47e4eb348d611f9af53f1038ffee/taming/modules/vqvae/quantize.py#L69

**Comment by rromb** [comment]
Thanks for pointing this out (see also #57), will be fixed soon.

**Comment by pesser** [comment]
Closed by #58 . Set `legacy=False` in the quantizer to use it. Thanks!
