### ISSUE TITLE
[Question] How to detect and grab a grid from an image

### ISSUE THREAD

**Issue by joe733** [CompVis/taming-transformers#49]
Hi, I'm new to this field, so as part of my studies I'm trying to detect and return a Sudoku grid from and image. I know I can use the [Hough lines transform](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html#hough-tranform-in-opencv) but it gets messy:

![image](https://user-images.githubusercontent.com/38415384/118583972-8bf43b00-b7b3-11eb-9811-589ade64d879.png)

It possible to detect grid more cleanly and efficiently?

**Comment by adeptflax** [comment]
I'm been trying figure out how to do image2image translation with this repo for the past few days. I think I figured it out. I'll write a guide on how to do this once I actually successfully trained a model. My issue #51.

**Comment by adeptflax** [comment]
@joe733 you could probably do this with pix2pixHD

**Comment by adeptflax** [comment]
I did on that issue how to do it a few days ago #51.

**Comment by joe733** [comment]
Nice, I'll go through

**Comment by adeptflax** [comment]
I realized I didn't do it correctly. I explained more on the issue thread.

**Comment by adeptflax** [comment]
You would have to train a vqgan model on Sudoku images and train another vqgan model on Sudoku line patterns. You would then train a transformer that would convert different the 2 images.

**Comment by joe733** [comment]
Hi, I'm still a beginner, so figuring things slowly. Thank you so much for the pointers!
