### ISSUE TITLE
Is the use of `map_pixels` in reconstruction_usage.ipynb intentional?

### ISSUE THREAD

**Issue by leod** [CompVis/taming-transformers#55]
Hi folks,

I've been trying to figure out the correct preprocessing for VQGAN models. In the [example notebook](https://colab.research.google.com/github/CompVis/taming-transformers/blob/master/scripts/reconstruction_usage.ipynb#scrollTo=ikPq5rvxXucQ&line=1&uniqifier=1), DALL-E's [`map_pixels`](https://github.com/lucidrains/DALLE-pytorch/blob/69375005aad0ac84aec0ead23fede6640e0eb5a4/dalle_pytorch/vae.py#L47) (i.e. `0.8*x+0.1`) is used for *all* models -- even for showing the input picture itself. Is this intentional?

Based on my tests, `map_pixels` is only needed for DALL-E; for other models, it causes images to turn out slightly darker. For reference, this screenshot is *with* `map_pixels` in `preprocess` (as in the example notebook):

![image](https://user-images.githubusercontent.com/100118/120924027-f3761a00-c6d1-11eb-91cc-67e1932623a0.png)

And this is what it looks like *without* `map_pixels`. DALL-E's model is thoroughly confused (which might be expected due to the mismatch with training), but for the other models we get lighter images:

![image](https://user-images.githubusercontent.com/100118/120924066-1e606e00-c6d2-11eb-9185-e2a981f1502b.png)

Based on this, I would conclude that the following functions should be used for preprocessing/postprocessing images for VQGAN. Is this correct?

```python
# replaced `map_pixels` by `2*img-1`
def preprocess(img, target_image_size=256):
    s = min(img.size)
    
    if s < target_image_size:
        raise ValueError(f'min dim for image {s} < {target_image_size}')
        
    r = target_image_size / s
    s = (round(r * img.size[1]), round(r * img.size[0]))
    img = TF.resize(img, s, interpolation=PIL.Image.LANCZOS)
    img = TF.center_crop(img, output_size=2 * [target_image_size])
    img = torch.unsqueeze(T.ToTensor()(img), 0)
    return 2*img - 1

# unchanged
def custom_to_pil(x):
  x = x.detach().cpu()
  x = torch.clamp(x, -1., 1.)
  x = (x + 1.)/2.
  x = x.permute(1,2,0).numpy()
  x = (255*x).astype(np.uint8)
  x = Image.fromarray(x)
  if not x.mode == "RGB":
    x = x.convert("RGB")
  return x
```

Any help would be appreciated.

Thanks!

**Comment by rromb** [comment]
Thanks for catching this, you are right! Should be fixed now

**Comment by leod** [comment]
Thank you very much, looks good! Closing this.
