### ISSUE TITLE
How to set the number of epochs to train?

### ISSUE THREAD

**Issue by Guthman** [CompVis/taming-transformers#56]
I feel stupid for asking, but I don't see it in the argument list. I've searched throughout the code as well to find a way to control this, but no dice. I'm training the model on a cluster system where local files on the node are deleted after a job ends (which is either when the shell script terminates or when the allocated time has passed). So I need a way to say 'train for X epochs' and when the Python script finishes I can copy the log directory to a safe place. 

Right now I'm calling `os.system('cp -r "TMPDIR"/logs $HOME/vqgan_output')` inside main.py (at on_train_batch_end()) but this is quite an ugly solution.

**Comment by adeptflax** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.trainer.html

I think you set lightning.trainer.params.min_epochs and lightning.trainer.params.max_epochs in the config.
