### ISSUE TITLE
Fine tuning existing model on new dataset

### ISSUE THREAD

**Issue by MartaTintore** [CompVis/taming-transformers#59]
Hi, thanks for the work!
I would like to know the easiest way to fine tune an existing model on a new dataset, not sure how to modify data loading process. Thanks!

**Comment by mathigatti** [comment]
Hi, did you find some solution for this?

**Comment by PineappleWill** [comment]
Hi, I notice your issue, I have the same question. Would you please tell me the solution?

**Comment by wnakano** [comment]
@MartaTintore  @mathigatti @PineappleWill 
I don't know if this is still something of interest to you or if you already solved it, but you can achieve that adding few lines of code in `main.py` right after `model = instantiate_from_config(config.model)`
```
model = instantiate_from_config(config.model)
model_path = "<ckpt-path>"
state = torch.load(model_path, map_location = 'cpu')['state_dict']
model.load_state_dict(state, strict = False)
```
just keep in mind that is still needed to align the model description in your `custom_vqgan.yaml` and the desired weights

**Comment by 2931089319** [comment]
God!So Thankkkkkkkkkkkkkkkkks!!!!!

> [@MartaTintore](https://github.com/MartaTintore) [@mathigatti](https://github.com/mathigatti) [@PineappleWill](https://github.com/PineappleWill) I don't know if this is still something of interest to you or if you already solved it, but you can achieve that adding few lines of code in `main.py` right after `model = instantiate_from_config(config.model)`
> 
> ```
> model = instantiate_from_config(config.model)
> model_path = "<ckpt-path>"
> state = torch.load(model_path, map_location = 'cpu')['state_dict']
> model.load_state_dict(state, strict = False)
> ```
> 
> just keep in mind that is still needed to align the model description in your `custom_vqgan.yaml` and the desired weights
