### ISSUE TITLE
where is the key code of the tansformer?

### ISSUE THREAD

**Issue by henbucuoshanghai** [CompVis/taming-transformers#7]

**Comment by rromb** [comment]
Hi there, thanks for checking out our code!
- The essential code for the transformer is defined by the class `GPT` at `taming/modules/transformer/mingpt.py` (which is basically the model implemented [here](https://github.com/karpathy/minGPT)) and trained via the pytorch-lightning module `Net2NetTransformer` in `taming/models/transformer/cond_transformer.py`.
- The pl-module defining the VQGAN is `VQModel` in `taming/models/vqgan.py`

Let us know if this does not answer your question.
