### ISSUE TITLE
index 183 is out of bounds for axis 0 with size 182 np.eye

### ISSUE THREAD

**Issue by ak9250** [CompVis/taming-transformers#8]
on this line
segmentation = np.eye(182)[segmentation]
this was with the default image in segmentation norway

**Comment by ak9250** [comment]
@pesser any update on this, I think it has to do with lossy compression being applied

**Comment by DenisSergeevitch** [comment]
Also having this problem, here is example of png file that works fine:
![test_2](https://user-images.githubusercontent.com/2140110/104209297-d0508280-5431-11eb-8e86-eb1b17c73c7c.png)

And file that causing `IndexError: index 255 is out of bounds for axis 0 with size 182` error:
![test_3](https://user-images.githubusercontent.com/2140110/104209344-dfcfcb80-5431-11eb-9542-d86ed3160eda.png)

What is the difference between them?

**Comment by pesser** [comment]
Cannot reproduce on the included segmentations. @DenisSergeevitch the difference is that the latter is an 8 bit gray+alpha png (try running `file <filename.png>` on the file). The segmentation pngs should be 8 bit grayscale pngs, i.e. the reported [`mode` on the Pillow image](https://pillow.readthedocs.io/en/3.0.x/handbook/concepts.html#modes) should be "L".
Many applications do not save in that format by default. Either make sure they do, or try something like
```
    segmentation = Image.open(segmentation_path)
    segmentation = segmentation.convert("L")
```
Of course, it should contain only values `< 182` - if some modification or compression produced values out of that range, you can always use something like
```
    segmentation = np.array(segmentation)
    segmentation = segmentation.clip(0, 181)
```
@ak9250 does that solve your issue, too? Just to make sure, this is what I get from the included norway segmentations:
```
from PIL import Image
import numpy as np
import hashlib

files = ["data/sflckr_segmentations/norway/25735082181_999927fe5a_b.png", 
         "data/sflckr_segmentations/norway/20099378793_cc2df820af_b.png"]

for segmentation_path in files:
    with open(segmentation_path, "rb") as f:
        content = f.read()
    print(segmentation_path, hashlib.md5(content).hexdigest())

    segmentation = Image.open(segmentation_path)
    assert segmentation.mode == "L", segmentation.mode

    segmentation = np.array(segmentation)
    print(segmentation.dtype, segmentation.shape, segmentation.min(), segmentation.max())

    segmentation = np.eye(182)[segmentation]
    assert segmentation.max() < 182
```
Output:
```
data/sflckr_segmentations/norway/25735082181_999927fe5a_b.png f0a6ba673b6887624f5baea8df08df1e
uint8 (683, 1024) 105 177
data/sflckr_segmentations/norway/20099378793_cc2df820af_b.png 2cccdaabd97ac1dcc4ccd4c489ff1f76
uint8 (768, 1024) 8 177
```

**Comment by DenisSergeevitch** [comment]
@pesser 
>The segmentation pngs should be 8 bit grayscale pngs

I'll try it, thank you, one more question: is it possible to feed to the model already colored version of segmentation map? 

I have tried to turn off this section:
```
  colorize = np.random.RandomState(1).randn(1,1,s.shape[-1],3)
  colorize = colorize / colorize.sum(axis=2, keepdims=True)
  s = s@colorize
  s = s[...,0,:]
  s = ((s+1.0)*127.5).clip(0,255).astype(np.uint8)
  s = Image.fromarray(s)
```

Color *.png should be in 8 bit too?

**Comment by DenisSergeevitch** [comment]
It worked for me, thank you ✨

**Comment by ak9250** [comment]
@pesser thanks this is what I have so far
```
    segmentation = Image.open(segmentation_path)
    segmentation = segmentation.convert("L")
    segmentation = np.array(segmentation)
    segmentation = segmentation.clip(0, 181)

    segmentation = np.eye(182)[segmentation]
    segmentation = torch.tensor(segmentation.transpose(2,0,1)[None]).to(dtype=torch.float32, device=model.device)
```

I am getting AttributeError("'NoneType' object has no attribute 'device'",)."

segmentation = torch.tensor(segmentation.transpose(2,0,1)[None]).to(dtype=torch.float32, device=model.device)"

**Comment by pesser** [comment]
@DenisSergeevitch Glad to hear! If you really need to work with an already colored version, you could try to recover the original labeling with something like
```
colorize = np.random.RandomState(1).randn(1,1,182,3)
colorize = colorize / colorize.sum(axis=2, keepdims=True)
segmentation=np.sum((colored[...,None]-colorize.transpose(0,1,3,2))**2,2).argmin(2)
```
but tbh I would not suggest going down that (error-prone) route :)

**Comment by pesser** [comment]
@ak9250 could this just be due to `model` being `None`?

**Comment by ak9250** [comment]
@pesser thanks i think it work this is the input and output
![testimg](https://user-images.githubusercontent.com/6818285/104217344-47255580-5409-11eb-9c03-6db1ad6e2f95.jpeg)
![outputtest](https://user-images.githubusercontent.com/6818285/104217353-4a204600-5409-11eb-97dd-4b74744c826e.jpeg)

**Comment by ak9250** [comment]
@DenisSergeevitch I tried yours as well
![523235](https://user-images.githubusercontent.com/6818285/104218599-f7478e00-540a-11eb-9371-9a14d40bef6f.jpeg)
