### ISSUE TITLE
What is the Validation sanity check for?

### ISSUE THREAD

**Issue by zimingzhong** [CompVis/taming-transformers#92]
It always takes several minutes to process a Validation sanity check. It is too slow. Can I reduce it?

**Comment by rromb** [comment]
Hi, 

it is a pytorch-lightning parameter that allows to check the validation loop before starting the actual training. You can reduce it by setting `--num_sanity_val_steps` in the command line. See also [here](https://forums.pytorchlightning.ai/t/validation-sanity-check/174/4) and [here](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer).

**Comment by zimingzhong** [comment]
Hi, 

Could you check my issue "there are no points" on Your work Geofree? Thank you.
