### ISSUE TITLE
how to train the conditional transformer, conditioned on vectors?

### ISSUE THREAD

**Issue by ali-design** [CompVis/taming-transformers#99]
Thank you for the great effort!
How can I train the conditional transformer when I would like to condition image on a vector (as opposed to depth map or class label)? Specifically how the config would look like?

**Comment by rromb** [comment]
Hi, 

one way to achieve this is to concatenate the conditioning vector and the outputs of the `tok_emb` layer in `minGPT` by feeding them into the forward, i.e. call gpt(data_idx, embeddings=conditioning_vectors). Note that the forward pass of `Net2NetTransformer` has to be adopted accordingly.

**Comment by ali-design** [comment]
That seems more like how to load the conditioning_vectors. But 
- how should we config the file?
- What do you mean by "he forward pass of Net2NetTransformer has to be adopted accordingly."?
Thank you.
